matrix:
  include:
    - language: node_js
      nodejs:
        - 12

      addons:
        apt:
          packages:
            - python-pygments
            - pyyaml

      before_install:
        - export PATH="$TRAVIS_BUILD_DIR/bin:$PATH"

      cache: yarn

    - language: python
      python:
        - "2.7"

      before_script:
        - cd tests
        
      script: 
        - python json-validator.py --directory ../content --extension .md
        - python yaml-validator.py --directory ../content --extension .md
