baseurl = "https://sensu-docs-site.herokuapp.com/"
languageCode = "en-us"
title = "Material Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Material"
	url    = "example/content/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "example/content/getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "example/content/adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "example/contentroadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "example/content/license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
