baseurl = ""
languageCode = "en-us"
title = "Sensu Docs"
metadataformat = "yaml"
canonifyURLs = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-39138312-17"
enableRobotsTXT = true
pygmentsUseClasses = true
ignoreFiles = ["sensu-doc-template.md"]
disableKinds = ["taxonomy", "taxonomyTerm"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

[["menu.sensu-core-1.0"]]
  name = "Moi API"
  url = "/"
  identifier = "api"

[params]
  # General information
  description = "Sensu is the industry-leading solution for multi-cloud monitoring at scale. Sensu's observability pipeline automates monitoring and offers deep visibility for multi-cloud environments. Built by operators, for operators, open source is at the heart of the product."
  copyright = ""

  # Repository
  provider = "GitHub"
  repo_url = "https://github.com/sensu/sensu-docs"

  version = "1.0"
  logo = "/images/sensu-logo-icon-dark@128px.png"
  favicon = "/images/favicon.png"

  permalink = "#"

  # Custom assets
  custom_css = []
  custom_js = []

  [params.palette]
    primary = "green"
    accent = "green"

  [params.font]
    text = "Ubuntu"
    code = "Ubuntu Mono"

  [params.products.sensu_go]
    identifier = "sensu-go"
    name = "Sensu Go"
    description = "The next-generation monitoring event pipeline"
    notice = "Replaces Sensu Core and Enterprise"
    weight = 1
    latest = "6.9"

    [[params.products.sensu_go.versions]]
    version = "6.9"
    platforms = []

    [[params.products.sensu_go.versions]]
    version = "6.8"
    platforms = []

    [[params.products.sensu_go.versions]]
    version = "6.7"
    platforms = []

    [[params.products.sensu_go.versions]]
    version = "6.6"
    platforms = []

    [[params.products.sensu_go.versions]]
    version = "6.5"
    platforms = []

  [params.products.sensu_core]
    identifier = "sensu-core"
    name = "Sensu Core"
    description = "The original monitoring event pipeline"
    notice = "End of life: December 31, 2019"
    weight = 2
    latest = "1.9"

    [[params.products.sensu_core.versions]]
    version = "1.9"
    platforms = [
      "Ubuntu/Debian",
      "RHEL/CentOS"
    ]

  [params.products.sensu_enterprise]
    identifier = "sensu-enterprise"
    name = "Sensu Enterprise"
    description = "The powerful and simple monitoring product, built on Sensu Core"
    notice = "End of life: March 31, 2020"
    weight = 3
    latest = "3.8"

    [[params.products.sensu_enterprise.versions]]
    version = "3.8"
    platforms = [
      "Ubuntu/Debian",
      "RHEL/CentOS"
    ]

  [params.products.sensu_enterprise_dashboard]
    identifier = "sensu-enterprise-dashboard"
    name = "Sensu Enterprise Dashboard"
    description = "The dashboard for Sensu Enterprise, built on Uchiwa"
    notice = "End of life: March 31, 2020"
    weight = 4
    latest = "2.16"

    [[params.products.sensu_enterprise_dashboard.versions]]
    version = "2.16"
    platforms = [
      "Ubuntu/Debian",
      "RHEL/CentOS"
    ]

  [params.products.uchiwa]
    identifier = "uchiwa"
    name = "Uchiwa"
    description = "An open source dashboard for Sensu Core"
    notice = "End of life: December 31, 2019"
    weight = 5
    latest = "1.0"

    [[params.products.uchiwa.versions]]
    version = "1.0"
    platforms = []

[social]
  twitter = "sensu"
  github = "sensu"
  email = ""

[blackfriday]
  extensions = ["laxHtmlBlocks"]
  smartypants = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
